"""empty message

Revision ID: 0829b0b16004
Revises: b74a4797d18d
Create Date: 2025-04-20 11:37:13.356231

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "0829b0b16004"
down_revision: Union[str, None] = "b74a4797d18d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "types_sports",
        "description",
        existing_type=mysql.VARCHAR(length=5000),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column(
        "upcoming_events",
        "description",
        existing_type=mysql.VARCHAR(length=3000),
        type_=sa.Text(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "upcoming_events",
        "description",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=3000),
        existing_nullable=False,
    )
    op.alter_column(
        "types_sports",
        "description",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=5000),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
