"""empty message

Revision ID: 0da3805015c4
Revises: abe1199b5146
Create Date: 2025-04-25 13:32:08.060634

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0da3805015c4"
down_revision: Union[str, None] = "abe1199b5146"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "athletes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("middle_name", sa.String(length=100), nullable=True),
        sa.Column("qualification", sa.String(length=1000), nullable=False),
        sa.Column("image", sa.String(length=500), nullable=False),
        sa.Column("type_sport_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["type_sport_id"], ["types_sports.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "coaches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("middle_name", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("image", sa.String(length=500), nullable=False),
        sa.Column("type_sport_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["type_sport_id"], ["types_sports.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("coaches")
    op.drop_table("athletes")
    # ### end Alembic commands ###
