"""empty message

Revision ID: 122dc4ae3ac8
Revises: ac4bb2cd4839
Create Date: 2025-04-26 12:51:50.421635

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "122dc4ae3ac8"
down_revision: Union[str, None] = "ac4bb2cd4839"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("organization_social_network")
    op.add_column(
        "organization",
        sa.Column("telegram_link", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "organization",
        sa.Column("vk_link", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "organization",
        sa.Column("whats_app_link", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "organization",
        sa.Column("rutube_link", sa.String(length=100), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization", "rutube_link")
    op.drop_column("organization", "whats_app_link")
    op.drop_column("organization", "vk_link")
    op.drop_column("organization", "telegram_link")
    op.create_table(
        "organization_social_network",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "name",
            mysql.ENUM("telegram", "vk", "whats_app", "rutube"),
            nullable=False,
        ),
        sa.Column("link", mysql.VARCHAR(length=255), nullable=False),
        sa.Column(
            "organization_id",
            mysql.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name="organization_social_network_ibfk_1",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
