"""empty message

Revision ID: 163d10bc6031
Revises: 689a85fe21c2
Create Date: 2025-05-03 12:10:45.291848

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "163d10bc6031"
down_revision: Union[str, None] = "689a85fe21c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization_sport_objects",
        sa.Column(
            "latitude",
            sa.Float(precision=32, decimal_return_scale=None),
            nullable=False,
        ),
    )
    op.add_column(
        "organization_sport_objects",
        sa.Column(
            "longitude",
            sa.Float(precision=32, decimal_return_scale=None),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization_sport_objects", "longitude")
    op.drop_column("organization_sport_objects", "latitude")
    # ### end Alembic commands ###
