"""empty message

Revision ID: 450b2b8bdd28
Revises: 0da3805015c4
Create Date: 2025-04-25 13:54:48.663371

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "450b2b8bdd28"
down_revision: Union[str, None] = "0da3805015c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization_info",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=1000), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "organization_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=1000), nullable=False),
        sa.Column("file", sa.String(length=500), nullable=False),
        sa.Column("organization_info_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_info_id"],
            ["organization_info.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("organization_documents")
    op.drop_table("organization_info")
    # ### end Alembic commands ###
