"""empty message

Revision ID: 6a4177511170
Revises: 9b9f7738363b
Create Date: 2025-08-21 10:01:51.570797

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "6a4177511170"
down_revision: Union[str, None] = "9b9f7738363b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "organization_sport_objects",
        "latitude",
        existing_type=mysql.DOUBLE(asdecimal=True),
        type_=sa.Float(precision=32),
        existing_nullable=False,
    )
    op.alter_column(
        "organization_sport_objects",
        "longitude",
        existing_type=mysql.DOUBLE(asdecimal=True),
        type_=sa.Float(precision=32),
        existing_nullable=False,
    )
    op.add_column("photo_news", sa.Column("order", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("photo_news", "order")
    op.alter_column(
        "organization_sport_objects",
        "longitude",
        existing_type=sa.Float(precision=32),
        type_=mysql.DOUBLE(asdecimal=True),
        existing_nullable=False,
    )
    op.alter_column(
        "organization_sport_objects",
        "latitude",
        existing_type=sa.Float(precision=32),
        type_=mysql.DOUBLE(asdecimal=True),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
