"""empty message

Revision ID: 9b9f7738363b
Revises: dae2028d55b7
Create Date: 2025-08-21 09:55:07.435980

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "9b9f7738363b"
down_revision: Union[str, None] = "dae2028d55b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "coaches", "description", existing_type=mysql.TEXT(), nullable=True
    )
    op.add_column(
        "document_category", sa.Column("order", sa.Integer(), nullable=False)
    )
    op.alter_column("news", "description", existing_type=mysql.TEXT(), nullable=True)
    op.add_column(
        "organization", sa.Column("logo", sa.String(length=500), nullable=False)
    )
    op.add_column(
        "organization", sa.Column("monday_hours", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "organization",
        sa.Column("tuesday_hours", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "organization",
        sa.Column("wednesday_hours", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "organization",
        sa.Column("thursday_hours", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "organization", sa.Column("friday_hours", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "organization",
        sa.Column("saturday_hours", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "organization", sa.Column("sunday_hours", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "organization_info", sa.Column("order", sa.Integer(), nullable=False)
    )
    op.add_column(
        "organization_info", sa.Column("url", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "organization_phones",
        sa.Column("division", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "organization_sport_objects",
        sa.Column("monday_hours", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "organization_sport_objects",
        sa.Column("tuesday_hours", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "organization_sport_objects",
        sa.Column("wednesday_hours", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "organization_sport_objects",
        sa.Column("thursday_hours", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "organization_sport_objects",
        sa.Column("friday_hours", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "organization_sport_objects",
        sa.Column("saturday_hours", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "organization_sport_objects",
        sa.Column("sunday_hours", sa.String(length=100), nullable=True),
    )
    op.alter_column(
        "organization_sport_objects",
        "latitude",
        existing_type=mysql.DOUBLE(asdecimal=True),
        type_=sa.Float(precision=32),
        existing_nullable=False,
    )
    op.alter_column(
        "organization_sport_objects",
        "longitude",
        existing_type=mysql.DOUBLE(asdecimal=True),
        type_=sa.Float(precision=32),
        existing_nullable=False,
    )
    op.drop_column("organization_sport_objects", "end_works")
    op.drop_column("organization_sport_objects", "start_works")
    op.alter_column(
        "types_sports", "description", existing_type=mysql.TEXT(), nullable=True
    )
    op.alter_column(
        "upcoming_events", "description", existing_type=mysql.TEXT(), nullable=True
    )
    op.alter_column(
        "vacancies", "description", existing_type=mysql.TEXT(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "vacancies", "description", existing_type=mysql.TEXT(), nullable=False
    )
    op.alter_column(
        "upcoming_events", "description", existing_type=mysql.TEXT(), nullable=False
    )
    op.alter_column(
        "types_sports", "description", existing_type=mysql.TEXT(), nullable=False
    )
    op.add_column(
        "organization_sport_objects",
        sa.Column("start_works", mysql.TIME(), nullable=False),
    )
    op.add_column(
        "organization_sport_objects",
        sa.Column("end_works", mysql.TIME(), nullable=False),
    )
    op.alter_column(
        "organization_sport_objects",
        "longitude",
        existing_type=sa.Float(precision=32),
        type_=mysql.DOUBLE(asdecimal=True),
        existing_nullable=False,
    )
    op.alter_column(
        "organization_sport_objects",
        "latitude",
        existing_type=sa.Float(precision=32),
        type_=mysql.DOUBLE(asdecimal=True),
        existing_nullable=False,
    )
    op.drop_column("organization_sport_objects", "sunday_hours")
    op.drop_column("organization_sport_objects", "saturday_hours")
    op.drop_column("organization_sport_objects", "friday_hours")
    op.drop_column("organization_sport_objects", "thursday_hours")
    op.drop_column("organization_sport_objects", "wednesday_hours")
    op.drop_column("organization_sport_objects", "tuesday_hours")
    op.drop_column("organization_sport_objects", "monday_hours")
    op.drop_column("organization_phones", "division")
    op.drop_column("organization_info", "url")
    op.drop_column("organization_info", "order")
    op.drop_column("organization", "sunday_hours")
    op.drop_column("organization", "saturday_hours")
    op.drop_column("organization", "friday_hours")
    op.drop_column("organization", "thursday_hours")
    op.drop_column("organization", "wednesday_hours")
    op.drop_column("organization", "tuesday_hours")
    op.drop_column("organization", "monday_hours")
    op.drop_column("organization", "logo")
    op.alter_column("news", "description", existing_type=mysql.TEXT(), nullable=False)
    op.drop_column("document_category", "order")
    op.alter_column(
        "coaches", "description", existing_type=mysql.TEXT(), nullable=False
    )
    # ### end Alembic commands ###
