"""empty message

Revision ID: b0422c5fc013
Revises: 6a4177511170
Create Date: 2025-08-25 11:23:50.759047

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "b0422c5fc013"
down_revision: Union[str, None] = "6a4177511170"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization", sa.Column("short_name", sa.String(length=100), nullable=False)
    )
    op.alter_column(
        "organization_sport_objects",
        "latitude",
        existing_type=mysql.DOUBLE(asdecimal=True),
        type_=sa.Float(precision=32),
        existing_nullable=False,
    )
    op.alter_column(
        "organization_sport_objects",
        "longitude",
        existing_type=mysql.DOUBLE(asdecimal=True),
        type_=sa.Float(precision=32),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "organization_sport_objects",
        "longitude",
        existing_type=sa.Float(precision=32),
        type_=mysql.DOUBLE(asdecimal=True),
        existing_nullable=False,
    )
    op.alter_column(
        "organization_sport_objects",
        "latitude",
        existing_type=sa.Float(precision=32),
        type_=mysql.DOUBLE(asdecimal=True),
        existing_nullable=False,
    )
    op.drop_column("organization", "short_name")
    # ### end Alembic commands ###
