"""empty message

Revision ID: b15a7be82e7f
Revises: b43dff2329c5
Create Date: 2025-04-27 11:29:43.878619

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "b15a7be82e7f"
down_revision: Union[str, None] = "b43dff2329c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "news",
        "date",
        existing_type=mysql.DATETIME(),
        type_=sa.Date(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "news",
        "date",
        existing_type=sa.Date(),
        type_=mysql.DATETIME(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
