"""empty message

Revision ID: b74a4797d18d
Revises: 40d75c24a4fd
Create Date: 2025-04-19 13:57:37.732873

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b74a4797d18d"
down_revision: Union[str, None] = "40d75c24a4fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "upcoming_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=3000), nullable=False),
        sa.Column("image", sa.String(length=500), nullable=False),
        sa.Column("type_sport_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["type_sport_id"], ["types_sports.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("upcoming_events")
    # ### end Alembic commands ###
