"""empty message

Revision ID: d53511ec71c4
Revises: 0223005da364
Create Date: 2025-05-03 12:41:52.724743

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "d53511ec71c4"
down_revision: Union[str, None] = "0223005da364"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization_sport_objects", "longitude")
    op.drop_column("organization_sport_objects", "latitude")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization_sport_objects",
        sa.Column("latitude", mysql.FLOAT(), nullable=False),
    )
    op.add_column(
        "organization_sport_objects",
        sa.Column("longitude", mysql.FLOAT(), nullable=False),
    )
    # ### end Alembic commands ###
