"""empty message

Revision ID: dae2028d55b7
Revises: d53511ec71c4
Create Date: 2025-05-03 12:42:21.372459

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dae2028d55b7"
down_revision: Union[str, None] = "d53511ec71c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization_sport_objects",
        sa.Column("latitude", sa.Float(precision=32), nullable=False),
    )
    op.add_column(
        "organization_sport_objects",
        sa.Column("longitude", sa.Float(precision=32), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization_sport_objects", "longitude")
    op.drop_column("organization_sport_objects", "latitude")
    # ### end Alembic commands ###
