"""empty message

Revision ID: e0f9178cb590
Revises: 450b2b8bdd28
Create Date: 2025-04-25 14:10:29.266838

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "e0f9178cb590"
down_revision: Union[str, None] = "450b2b8bdd28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization_documents",
        sa.Column("category", sa.String(length=1000), nullable=True),
    )
    op.alter_column(
        "organization_documents",
        "organization_info_id",
        existing_type=mysql.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "organization_info",
        "description",
        existing_type=mysql.TEXT(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "organization_info",
        "description",
        existing_type=mysql.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "organization_documents",
        "organization_info_id",
        existing_type=mysql.INTEGER(),
        nullable=False,
    )
    op.drop_column("organization_documents", "category")
    # ### end Alembic commands ###
