"""empty message

Revision ID: e4a0b525d63f
Revises: e0f9178cb590
Create Date: 2025-04-26 09:47:59.413257

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "e4a0b525d63f"
down_revision: Union[str, None] = "e0f9178cb590"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "organization_documents",
        sa.Column("category_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        None,
        "organization_documents",
        "document_category",
        ["category_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("organization_documents", "category")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization_documents",
        sa.Column("category", mysql.VARCHAR(length=1000), nullable=True),
    )
    op.drop_constraint(None, "organization_documents", type_="foreignkey")
    op.drop_column("organization_documents", "category_id")
    op.drop_table("document_category")
    # ### end Alembic commands ###
